spring:
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}/${mysql.database}?createDatabaseIfNotExist=true
    hikari:
      auto-commit: false
      connection-timeout: 250
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: vehicle-rent-master
  liquibase:
    change-log: liquibase/master.yaml
    enabled: ${liquibase.enabled:true}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: ${mysql.ddl-auto}
    properties:
      #      "[hibernate.dialect]": org.hibernate.dialect.MySQL8Dialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      "[jakarta.persistence.sharedCache.mode]": ENABLE_SELECTIVE
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4
springdoc:
  swagger-ui:
    path: /swagger